image: python:3.12

stages:
  - prepare
  - test
  - report
  - deploy

cache:
  paths:
    - .pip-cache/

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

prepare:
  stage: prepare

  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt

test:
  stage: test

  script:
    - pytest --alluredir=allure-results

  artifacts:
    when: always
    paths:
      - allure-results
      - screenshots

report:
  stage: report

  script:
    - apt-get update
    - apt-get install -y default-jre wget unzip
    - wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
    - unzip allure-2.29.0.zip
    - ./allure-2.29.0/bin/allure generate allure-results -o public

  artifacts:
    when: always
    paths:
      - public

deploy:
  stage: deploy

  script:
    - echo "Deploying Allure Report"

  artifacts:
    paths:
      - public

  only:
    - main